### ISSUE TITLE
Error with LineFilters when running specific example in Scenario outline

### ISSUE THREAD

**Issue by ricardorlg-aval** [serenity-bdd/serenity-cucumber5#11]
I see that when running an specific example serenity will report the example name as null, because this 
```java
if (lineFiltersContainFeaturePath(featurePath)) {
            return false;
```
will always return false, What is the idea behind that logic? I made a test removing it from `examplesAreNotExcluded` and `tableRowIsNotExcludedBy` methods and now the report is correct. I don't want to make a PR without knowing the idea behind the original logic.

@cliviu, @wakaleo can u guide me through this.

**Comment by cliviu** [comment]
hi @ricardorlg-aval , thanks for spotting the problem. It was related with the method `lineFiltersContainFeaturePath(featurePath)`. But the line should not be completely removed. The test condition was wrong there, it should have actually been inverted, like `!lineFiltersContainFeaturePath(featurePath)`

**Comment by ricardorlg-aval** [comment]
Hi @cliviu , perfect, I see that u already make the PR with the fix, I will remove mine then, now my next question @wakaleo should we make this change too for cucumber4 repo?.
