### ISSUE TITLE
When are we releasing this versions?, our projects are desperately looking to use cucumber 5 and 6 feature, but Serenity isn't yet supporting?  

### ISSUE THREAD

**Issue by venkat675** [serenity-bdd/serenity-cucumber5#15]

**Comment by wakaleo** [comment]
Which version are you referring to?

**Comment by venkat675** [comment]
We are looking to use latest cucumber version **5.7.0** or **5.6.0**, these versions have lot of new good BDD features.  but the latest serenity-cucumber5 **2.2.5** uses cucumber **5.5.0**.  please let me know  when are you planning to upgrade this.

Also, cucumber 6.1.1 is released, are we going to release new serenity version to support cucumber6 ?

**Comment by wakaleo** [comment]
We are looking into what is needed to upgrade to Cucumber 6.

**Comment by venkat675** [comment]
ok, thanks. 
And, thanks again for this wonderful library which makes automation process lot easier. We are looking forward to use cucumber 6 with serenity.
