### ISSUE TITLE
Cucumber jvm version 6.4.0 is not compatible with serenity cucumber 5

### ISSUE THREAD

**Issue by srilakshmishankar** [serenity-bdd/serenity-cucumber5#17]
I get below error when using serenity cucumber5  version 2.2.5 with cucumber jvm 6.4.0
cucumber jvm used: https://mvnrepository.com/artifact/io.cucumber/cucumber-java8

Works fine till  cucumber jvm version 5.7.0, so problem is from version 6.0.0

Error:

![Screenshot 2020-08-04 at 12 47 08 AM](https://user-images.githubusercontent.com/46483554/89234381-27813a00-d5ec-11ea-9a40-a8d6ce074328.png)

Runner class:
`import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    features = "src/test/resources/stories/",
    glue = "com/test/bdd",
    plugin = {"pretty"})
public class TestRunner {}`

Error in CucumberSerenityRunner.java

![Screenshot 2020-08-04 at 12 56 08 AM](https://user-images.githubusercontent.com/46483554/89234918-6368cf00-d5ed-11ea-87a6-a073d0e36a76.png)

 
Please let me know if any detail is missing. It is very easily reproducible.

**Comment by wakaleo** [comment]
serenity-cucumber-5 is only compatible with Cucumber 5.

**Comment by srilakshmishankar** [comment]
Thanks for the quick reply. Will it be supported anytime soon?

**Comment by wakaleo** [comment]
Cucumber 6 has breaking changes so it will be supported in a new module in the upcoming versions of serenity

**Comment by srilakshmishankar** [comment]
Alright, thanks then I will close this. Looking forward for serenity-cucumber-6.
